#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 04 15:21:51 EST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0
[ -z "$LIBRARY_PATH" ] && export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu || export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH

# catch pipeline exit status
set -Eeuo pipefail

# set simulation library paths
export xv_cxl_lib_path="/tools/Xilinx/${SIM_VER_XSIM}/data/xsim"
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path="/tools/Xilinx/${SIM_VER_XSIM}/data/simmodels/xsim/${SIM_VER_XSIM}/lnx64/${GCC_VER_XSIM}/systemc/protected"
xv_ext_lib_path="/tools/Xilinx/${SIM_VER_XSIM}/data/simmodels/xsim/${SIM_VER_XSIM}/lnx64/${GCC_VER_XSIM}/ext"
xv_lib_path="/tools/Xilinx/2025.2/Vivado/lib/lnx64.o/Ubuntu/22:/tools/Xilinx/2025.2/Vivado/lib/lnx64.o/Ubuntu:/tools/Xilinx/2025.2/Vivado/lib/lnx64.o"

xv_ref_path=${VIVADO_LOC:-"/tools/Xilinx/2025.2/Vivado"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

# set shared library paths
export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$xv_ref_path/data/xsim/ip/noc_sc_v1_0_0:$xv_ref_path/data/simmodels/xsim/${SIM_VER_XSIM}/lnx64/${GCC_VER_XSIM}/ext/protobuf:$xv_ref_path/data/xsim/ip/sim_qdma_cpp_v1_0:$xv_ref_path/data/xsim/ip/axi_tlm_ext_v1_0:$xv_ref_path/data/xsim/ip/remote_port_c_v4:$xv_ref_path/data/xsim/ip/sim_qdma_sc_v1_0:$xv_ref_path/data/xsim/ip/xtlm_simple_interconnect_v1_0:$xv_ref_path/data/xsim/ip/common_cpp_v1_0:$xv_ref_path/data/xsim/ip/debug_tcp_server_v1:$xv_ref_path/data/xsim/ip/common_rpc_v1:$xv_ref_path/data/simmodels/xsim/${SIM_VER_XSIM}/lnx64/${GCC_VER_XSIM}/systemc/protected/noc_v1_0_0:$xv_ref_path/data/xsim/ip/xtlm:$xv_ref_path/data/xsim/ip/remote_port_sc_v4:$xv_ref_path/data/xsim/ip/emu_perf_common_v1_0:$xv_ref_path/data/xsim/ip/rwd_tlmmodel_v1:$LD_LIBRARY_PATH

# simulate design
echo "xsim ext_platform_part_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:ext_platform_part_wrapper_sim_wrapper} -tclbatch ext_platform_part_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_5156.protoinst" -protoinst "protoinst_files/bd_152a.protoinst" -protoinst "protoinst_files/bd_a217.protoinst" -protoinst "protoinst_files/bd_4673.protoinst" -protoinst "protoinst_files/bd_61d2.protoinst" -protoinst "protoinst_files/ext_platform_part.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -log simulate.log -gui  $*"
xsim ext_platform_part_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:ext_platform_part_wrapper_sim_wrapper} -tclbatch ext_platform_part_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_5156.protoinst" -protoinst "protoinst_files/bd_152a.protoinst" -protoinst "protoinst_files/bd_a217.protoinst" -protoinst "protoinst_files/bd_4673.protoinst" -protoinst "protoinst_files/bd_61d2.protoinst" -protoinst "protoinst_files/ext_platform_part.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -log simulate.log -gui  $*

